### ISSUE TITLE
dbt integration/bootstram missing target

### ISSUE THREAD

**Issue by geoHeil** [sdf-labs/sdf-cli#21]
**Describe the bug**

Trying to explore from/with dbt:

```
sdf dbt init
   Finished dbt in 0.329 secs

error: SDF1013: YAML error: missing field `target`
```

Fails. However, I have a `profiles.yml` file sitting in my current directory looking like:

```
flags:
  send_anonymous_usage_stats: False

my_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: "{{ env_var('WAREHOUSE_SCHEMA', 'bar_dev') }}"
      path: ./analytics_database_dev.duckdb
      threads: 2
    prod:
      type: duckdb
      schema: "{{ env_var('WAREHOUSE_SCHEMA', 'bar') }}"
      path: /path/to/prod/analytics_database_prod.duckdb
      threads: 4

```

**To Reproduce**
1. create a dummy dbt project with duckdb
2. have it set up as outlined above
3. run `dbt compile`
4. run `sdf dbt init`
5. See error

**Expected behavior**
sdf init from dbt project with duckdb to work

**Additional context**

- sdf version is 0.5.16
